global:
  domain: c-4199fbe.kyma.ondemand.com
  imagePullSecret:
    name: {}
srv:
  bindings:
    destination:
      serviceInstanceName: 'destination'
    messaging:
      serviceInstanceName: event-mesh
    db:
      serviceInstanceName: hana
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: nidhimurkute/kyma-cap-s4ems-srv
    tag: latest
  env:
  - name: PUBLISHER_URL
    value: http://eventing-publisher-proxy.kyma-system.svc.cluster.local/publish
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
  additionalVolumes:
    - name: connectivity-secret
      volumeMount:
        mountPath: /bindings/connectivity
        readOnly: true
      projected:
        sources:
          - secret:
              name: <kyma-cap-s4ems-connectivity-secret>
              optional: false
          - secret:
              name: <kyma-cap-s4ems-connectivity-secret>
              optional: false
              items:
                - key: token_service_url
                  path: url
          - configMap:
              name: "{{ .Release.Name }}-connectivity-proxy-info"
              optional: false
destination:
  serviceOfferingName: 'destination'
  servicePlanName: 'lite'
  parameters:
    version: '1.0.0'
    HTML5Runtime_enabled: true
event-mesh:
  serviceOfferingName: enterprise-messaging
  servicePlanName: default
hana-deployer:
  image:
    repository: nidhimurkute/kyma-cap-s4ems-db
    tag: latest
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5-apps-deployer:
  env:
    SAP_CLOUD_SERVICE: com.bp.businesspartners
  image:
    repository: nidhimurkute/kyma-cap-s4ems-html5-deployer
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-configmap"
backendDestinations:
  srv-binding: 
      service: srv
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: kyma-cap-s4ems
    tenant-mode: dedicated
namespace: nidhi
gitusername: TXVya3V0ZU5pZGhp
gitpassword: Z2hwX2tlVjRQWUZ0cFYxRWtkWUhlWDRjMWtIZkZZWHdHVzA3Z1l4Mg==
giturl: https://github.com/MurkuteNidhi/kymacustomlogicw13.git
gitbranch: cw19
  
functionshttpproxy: https://connectivity-proxy.kyma-system.svc.cluster.local:20003
functionsenv: '{ "name":"s4h", "attachmentSrvApi":"API_CV_ATTACHMENT_SRV", "businessPartnerSrvApi":"API_BUSINESS_PARTNER", "businessObjectTypeName" : "BUS1006" }'
