
---
apiVersion: v1
kind: Config
current-context: garden-kyma--c-4199fbe-external
clusters:
- name: garden-kyma--c-4199fbe-external
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQU9CREJUU09HaUowdkx2WXNuVTFQUWN3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpNd05qQTJNRFUwTmpFNFdoY05Nek13TmpBMk1EVTBOakU0V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEdyCk5UWXVHZlZHanpMekF0SGQ0UWgxTFcxOHlzbjFIOVVBN0tRTDlJTGxGaFhJdkRvb3FwRVVmU3loeXRSUUIwN2UKWnhUWXRwalNXSmRCNmhtR3dOa3lpQkdOSUdObng2aWkrS2IxeC96ZUNCL1c5UG0yb25xRWZjVklSbm1seXUzKwp0OHprUHZRL09nVUJIMFdSUnZZaGwxbGJjRHFtRFYvNnZPUUp6alFSaHFRczRTRG54NDJSejF5eEZqN1pHL0taCkQ4QzkydnpVN2Nva01qY1VBMExvSVlOWTBmY0JyTU1uYWFRc1psak1yQlNXWnV1Y0xjTmg1cVlnZFhmVEVCUTgKWUZ0bjFYMUs5TWFPTkJyaVIxRStQam9WdnNRYmxZUnZseTBhcG9wdktvQ051QnNCSDNBR3JEM2I4Qnh2Zmt4awpFTDU4QjI4VHhsTlhRNStselNFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJakY1ZEtXY0lMcU1PUWx3Yk9RcEJUVUdYbVZNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBaStlTjNVUytZdThvVEhZMmVob2FuM2tiRm9PZlFIWXA3VzR4VEZORU1nQ1BCZUkwNgpvKzNMdUhxQmo0VjdoQTlCNXJxSEZXa3FxSmpMY0t0SlYwUjFhb2MvY3d2eU16UkppMU9IZFVzM1lnRC8veXBOCm5od05nbHN1WFRmeGgzN2k0WmhXcTRWS2FMcWtlUVEvWTBKSkpmcFNZL2RsMUJKTU43WEdIVkFnTTFJSDRFaFgKenFwVnJkak1sa3M2RU51U1VGSWJobE1sN2dSb3IyVXZrZy9sVVcvTlVQMVFSZnFVNkc0QnMzU244eDB1c2wzNwo1blJIeHdqMk0xcjVseVl5aC9DYWlkVzdLYlpaUXNOZHlDNXFFUWZFWGhMdHA5ZnU2b2FJWE9sT2VmODd2SStpCktHN1JYOTdkV2czWkVBYXljcERLa0M0cG9IR3NyVUIvbnBsawotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-4199fbe.kyma.ondemand.com
contexts:
- name: garden-kyma--c-4199fbe-external
  context:
    cluster: garden-kyma--c-4199fbe-external
    user: garden-kyma--c-4199fbe-external
users:
- name: garden-kyma--c-4199fbe-external
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
